---
- hosts: 172.31.1.30
  become: yes
  tasks:
  - include_tasks: mytags.yml
  - name: i want to install webserver
    apt:
     name: apache2
     state: present
  - name: i want to start server
    service:
      name: apache2
      state: started
