---
- hosts: 172.31.1.30
  become: yes
  tasks:
    - name: i want to install git tree wget.....etc
      apt: 
        name: "{{ item }}"
        state: present
      loop:
        - git
        - tree
        - wget