---
- hosts: all
  become: yes
  tasks:
  - name: i want to install a webserver on redhat
    yum:
      name: httpd
      state: present
  - name: i want to start webserver
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"  