---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install a webserver on redhat
    yum:
      name: "{{myredhatserver}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want to start webserver
    service:
      name: "{{myredhatserver}}"
      state: started
    when: ansible_os_family=="RedHat" 

  - name: i want to install a ubuntu webserver
    apt:
      name: "{{myubuntuserer}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver
    service:
      name: "{{myubuntuserer}}"
      state: started
    when: ansible_os_family=="Debian"