---
- hosts: 172.31.1.30
  become: yes
  tasks:
    - name: i want to install git
      apt:
        name: git
        state: present
      tags: git
    - name: i want ti install tree
      apt:
        name: tree
        state: present
      tags: tree
    - name: i want to install wget
      apt:
        name: wget
        state: present
      tags: wget
