---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install a ubuntu webserver
    apt:
      name: apache2
      state: present
  - name: i want to start webserver
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"
  - name: i want to install a webserver on redhat
    yum:
      name: httpd
      state: present
  - name: i want to start webserver
    serveice:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"
