---
- hosts: 172.31.1.30
  become: yes
  tasks:
   - name: i want to install web server
     apt:
      name: apache2
      state: present
    
   - name: i want to start web server
     service:
        name: apache2
        state: started
   - name: cange the index file into my own data
     templete:
      sorce: sorce.j2
      dest: /var/www/html/index.html