---
- name: copy tomcat user config file into node side
  template:
    src: /templates/mytomcatuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
- name: For the Manager app
  template:
    src: /templates/mytommanager.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml
- name: For the Host Manager app
  template:
    src: /templates/myhostmanager.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml